### ISSUE TITLE
Roll out plan

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#73]
## PHASE 1 - SOFT ROLL OUT FOR ONF
On 02/12 until 02/18 
- validate identities but do not block merge
- use this as an exercise to improve the front end / flow to reduce need of training

Deploy on:
- [x] `github.com/onosproject` and `github.com/stratumproject`: report status but do not make required status (ask Thomas/Brian)
-  [x] `gerrit.onosproject.org`: turn off enforcing but print message returned by the function (leave existing CLA validation on) (Zack)

## PHASE 2 - SOFT ROLL OUT TO PREVIOUS CONTRIBUTORS
On 02/20
-  [x] Send email to everyone about new tool asking to sign new CLA

## PHASE 3 - HARD ROLL OUT
On 03/01 for all ONF repos
-  [x] Enforce status checks on Github and turn enforcement on and disable individual CLA on Gerrit

**Comment by zdw** [comment]
Clarification:

During Phase 2, we roll out the CLA tool to all ONF GitHub/Gerrit repos, but don't enforce.

Phase 3 is when we fully enforce the CLA

**Comment by ccascone** [comment]
Installed GitHub app to all repos in `github.com/onosproject`. PR status are reported as expected.
The app is  available at: https://github.com/apps/onf-cla-manager

**Comment by zdw** [comment]
Installed Gerrit hook on `gerrit.onosproject.org`.  Having an issue with this currently as people who have signed are still getting the message that they haven't signed the CLA.

Also, Gerrit docs on hooks are somewhat ambiguous - turns out the hook name should be `commit-recieved` per changes in how they're invoked: https://www.gerritcodereview.com/2.14.html#behavior-change-in-ref-update-hook

**Comment by ccascone** [comment]
The issue has been fixed in #102

**Comment by zdw** [comment]
Enabled on gerrit.opencord.org

**Comment by zdw** [comment]
Enabled on omec-project repos

**Comment by ccascone** [comment]
Started tagging open issues that prevent the final roll-out phase as `blocker`

**Comment by zdw** [comment]
This is done, modulo some of the Github repos
